apiVersion: apps/v1
kind: Deployment
metadata:
  name: innovatech-backend
  namespace: innovatech
spec:
  strategy:
    type: Recreate
  replicas: 2
  selector:
    matchLabels:
      app: innovatech-backend
  template:
    metadata:
      labels:
        app: innovatech-backend
    spec:
      containers:
        - name: backend
          image: 114680401577.dkr.ecr.us-east-1.amazonaws.com/innovatech-backend-despachos:eks-v1
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "innovatech-db"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: DB_NAME
              value: "innovatech" # Corregido para que coincida exactamente con MySQL
            - name: DB_PORT
              value: "3306"
          resources:
            requests:
              cpu: "50m"      # Ajustado un poco más bajo para que el clúster estudiantil lo asigne de inmediato
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"