apiVersion: apps/v1
kind: Deployment
metadata:
  name: innovatech-ventas
  namespace: innovatech
spec:
  strategy:
    type: Recreate
  replicas: 2
  selector:
    matchLabels:
      app: innovatech-ventas
  template:
    metadata:
      labels:
        app: innovatech-ventas
    spec:
      containers:
        - name: ventas-backend
          # Apunta a la imagen de tu repositorio de ECR para ventas
          image: 114680401577.dkr.ecr.us-east-1.amazonaws.com/innovatech-backend-ventas:${IMAGE_TAG}
          ports:
            - containerPort: 8080 # Spring Boot suele usar el 8080 por defecto
          env:
            - name: DB_HOST
              value: "innovatech-db"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: DB_NAME
              value: "innovatech_ventas_db" # Ajusta si tu base de datos de ventas se llama distinto
            - name: DB_PORT
              value: "3306"
            # Si tu Spring Boot necesita perfiles activos, puedes descomentar las siguientes líneas:
            # - name: SPRING_PROFILES_ACTIVE
            #   value: "prod"

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"