apiVersion: v1
kind: Service
metadata:
  name: innovatech-db # Ajustado para que coincida con el DB_HOST de tus backends
  namespace: innovatech
spec:
  ports:
    - port: 3306
  selector:
    app: innovatech-db
  clusterIP: None # Se suele dejar en None (Headless Service) para bases de datos en Kubernetes