apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: innovatech # Cambiado de tienda a innovatech
type: Opaque
data:
  # Recuerda que en el archivo original del profesor, este valor está codificado en Base64.
  # Deja el mismo hash/valor codificado que venía en tu ejemplo original para mantener la misma contraseña.
  MYSQL_ROOT_PASSWORD: dGVzdDEyMzQ= # Reemplaza por el valor exacto que viene en tu ejemplo