apiVersion: apps/v1
kind: Deployment
metadata:
  name: innovatech-db
  namespace: innovatech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: innovatech-db
  template:
    metadata:
      labels:
        app: innovatech-db
    spec:
      # 👇 El secreto que creamos para dar el pase de autenticación
      imagePullSecrets:
        - name: ecr-registry-helper
      containers:
        - name: mysql
          # 👇 TU URI DE ECR QUEDA INTACTA Y PERFECTA COMO PIDE LA RÚBRICA
          image: 114680401577.dkr.ecr.us-east-1.amazonaws.com/innovatech-db:latest
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: "innovatech"
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          emptyDir: {}